name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Copy files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/root/nextjs-app"

    - name: Setup Node.js and install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/nextjs-app
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
          fi
          npm install -g pm2
          npm install
          
          cat > .env << EOF
          NEXT_PUBLIC_TRELLO_API_KEY=${{ secrets.NEXT_PUBLIC_TRELLO_API_KEY }}
          NEXT_PUBLIC_TRELLO_API_TOKEN=${{ secrets.NEXT_PUBLIC_TRELLO_API_TOKEN }}
          EOF
          
          npm run build
          pm2 delete nextjs-app || true
          pm2 start npm --name "nextjs-app" -- start
          pm2 save
          pm2 startup
